# Generated by Django 4.2.17 on 2025-01-14 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_username', models.CharField(max_length=20, null=True)),
                ('full_names', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('area_specialisation', models.TextField(null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('extra_data', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'mentor',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_username', models.CharField(max_length=10, null=True)),
                ('full_names', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('home_address', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('college_date', models.CharField(max_length=100, null=True)),
                ('college_considering', models.TextField(null=True)),
                ('majoring_courses', models.TextField(null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.TextField(null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(max_length=20, null=True)),
                ('university_name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('courses_offered', models.TextField(null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('extra_data', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'university',
            },
        ),
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100, null=True)),
                ('course_name', models.CharField(max_length=100, null=True)),
                ('duration', models.CharField(max_length=100, null=True)),
                ('fee', models.CharField(max_length=100, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('extra_data', models.TextField(max_length=100, null=True)),
                ('university_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='uniselect.universitymodel')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
